language: node_js
node_js:
  - 14

install:
  - npm i
script:
  - npm test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

env:
  global:
    - COVERALLS_PARALLEL=true

notifications:
  webhooks: https://coveralls.io/webhook
