language: node_js
node_js:
  - 14

install:
  - npm i
#script:
#  - npm test

env:
  global:
    - COVERALLS_PARALLEL=true

jobs:
  include:
    - script: COVERALLS_FLAG_NAME=Test npm test
notifications:
  webhooks: https://coveralls.io/webhook
