language: node_js
node_js:
  - 14

install:
  - npm i

before_script:
  - git submodule update --init

script:
  - npm test
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

notifications:
  webhooks: https://coveralls.io/webhook
